Example 068: An ordered collection of values in JSON-LD-expanded
---
- "@id": http://example.org/people#joebob
  http://xmlns.com/foaf/0.1/nick:
  - "@list":
    - "@value": joe
    - "@value": bob
    - "@value": jaybee
