Example 112: Coercing Values to Strings-compacted
---
"@context":
  "@vocab": http://example.com/
  date:
    "@type": http://www.w3.org/2001/XMLSchema#date
  en:
    "@language": en
  iri:
    "@type": "@id"
plain:
- string
- true
- 1
date: '2018-02-16'
en: English
iri: http://example.com/some-location
