Example 144: Same example with a list of values in JSON-LD
---
"@context":
  foaf: http://xmlns.com/foaf/0.1/
"@id": http://example.org/people#joebob
"@type": foaf:Person
foaf:name: Joe Bob
foaf:nick:
  "@list":
  - joe
  - bob
  - jaybee
